rust_library(
    name = "rue-error",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-span:rue-span",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "rue-error-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-span:rue-span",
    ],
)
