extra_srcs = [
    "examples/expected_type.rs",
    "examples/expected_type.svg",
    "examples/footer.rs",
    "examples/footer.svg",
    "examples/format.rs",
    "examples/format.svg",
    "examples/multislice.rs",
    "examples/multislice.svg",
]
