//! Stack alignment verification for AArch64.
//!
//! This module provides compile-time verification that the stack remains properly
//! aligned throughout function execution. The AAPCS64 ABI requires SP to be 16-byte
//! aligned at all times.
//!
//! # Background
//!
//! Unlike x86-64 where alignment is only required at call sites, AArch64 requires
//! the stack pointer to be 16-byte aligned at all times. Many AArch64 instructions
//! that access [SP] will fault if SP is not 16-byte aligned.
//!
//! # Verification Strategy
//!
//! We track a "stack depth" representing how many bytes have been pushed relative
//! to the aligned state after the prologue. Instructions that modify the stack
//! update this depth:
//!
//! - `stp x1, x2, [sp, #-16]!`: depth += 16 (store pair, pre-decrement)
//! - `ldp x1, x2, [sp], #16`: depth -= 16 (load pair, post-increment)
//! - `bl symbol`: verify depth % 16 == 0 (SP must be aligned at call)
//!
//! Note: The prologue is generated by the emitter, not present in the MIR. The
//! prologue ends with SP 16-byte aligned, so we start verification with depth = 0.
//!
//! # Limitations
//!
//! This verification pass operates on the instruction stream before emission,
//! when the prologue hasn't been added yet. We verify that the body of the function
//! maintains alignment assuming the prologue left SP aligned.
//!
//! The prologue's alignment is correct by construction (see `emit_prologue` in emit.rs).

use std::collections::HashMap;

use super::mir::{Aarch64Inst, Aarch64Mir, LabelId, Operand, Reg};
use gruel_error::{CompileError, CompileResult, ErrorKind};

/// Verifies that the stack is properly aligned throughout function execution.
///
/// This checks that:
/// 1. All call instructions occur when SP is 16-byte aligned
/// 2. STP/LDP sequences are balanced within basic blocks
/// 3. Control flow joins have consistent stack depths
///
/// # Arguments
///
/// * `mir` - The MIR instructions to verify (post-regalloc, pre-emit)
///
/// # Returns
///
/// `Ok(())` if verification passes, or `Err(CompileError)` with details about
/// the first alignment violation found.
pub fn verify_stack_alignment(mir: &Aarch64Mir) -> CompileResult<()> {
    let mut verifier = StackVerifier::new();
    verifier.verify(mir)
}

/// Internal state for stack verification.
struct StackVerifier {
    /// Stack depth at each label (for join point verification).
    /// After prologue, depth should be 0 (aligned).
    label_depths: HashMap<LabelId, i64>,
    /// Current stack depth in bytes relative to 16-byte aligned SP.
    /// 0 = aligned, 8 = misaligned by 8, etc.
    current_depth: i64,
}

impl StackVerifier {
    fn new() -> Self {
        Self {
            label_depths: HashMap::new(),
            current_depth: 0,
        }
    }

    fn verify(&mut self, mir: &Aarch64Mir) -> CompileResult<()> {
        // First pass: collect label positions and do basic verification
        for (idx, inst) in mir.iter().enumerate() {
            self.verify_instruction(idx, inst)?;
        }
        Ok(())
    }

    fn verify_instruction(&mut self, idx: usize, inst: &Aarch64Inst) -> CompileResult<()> {
        match inst {
            // Store pair with pre-decrement: stp x1, x2, [sp, #offset]!
            // This pushes two registers onto the stack
            Aarch64Inst::StpPre { offset, .. } => {
                // offset is typically negative (e.g., -16 to allocate 16 bytes)
                // depth increases by |offset|
                self.current_depth += (-*offset) as i64;
            }

            // Load pair with post-increment: ldp x1, x2, [sp], #offset
            // This pops two registers from the stack
            Aarch64Inst::LdpPost { offset, .. } => {
                // offset is typically positive (e.g., 16 to deallocate 16 bytes)
                // depth decreases by offset
                self.current_depth -= *offset as i64;
            }

            // SubImm on SP: allocates stack space
            Aarch64Inst::SubImm { dst, src, imm } => {
                if is_sp(dst) && is_sp(src) {
                    // sub sp, sp, #imm → increases depth (allocates)
                    self.current_depth += *imm as i64;
                }
            }

            // AddImm on SP: deallocates stack space
            Aarch64Inst::AddImm { dst, src, imm } => {
                if is_sp(dst) && is_sp(src) {
                    // add sp, sp, #imm → decreases depth (deallocates)
                    self.current_depth -= *imm as i64;
                }
            }

            // Call instructions require 16-byte alignment
            Aarch64Inst::Bl { .. } => {
                // At a call site, SP must be 16-byte aligned.
                // Unlike x86-64, the return address goes into LR, not pushed to stack,
                // so the callee sees SP at the same alignment as the caller.
                if self.current_depth % 16 != 0 {
                    return Err(self.alignment_error(
                        idx,
                        inst,
                        format!(
                            "call requires 16-byte aligned SP, but stack is {} bytes off",
                            self.current_depth % 16
                        ),
                    ));
                }
            }

            // Labels mark potential join points
            Aarch64Inst::Label { id } => {
                if let Some(&expected_depth) = self.label_depths.get(id) {
                    // We've seen a jump to this label before
                    if expected_depth != self.current_depth {
                        return Err(self.alignment_error(
                            idx,
                            inst,
                            format!(
                                "control flow join has inconsistent stack depth: expected {}, got {}",
                                expected_depth, self.current_depth
                            ),
                        ));
                    }
                } else {
                    // First time seeing this label, record current depth
                    self.label_depths.insert(*id, self.current_depth);
                }
            }

            // Jump instructions record target depths
            Aarch64Inst::B { label }
            | Aarch64Inst::BCond { label, .. }
            | Aarch64Inst::Bvs { label }
            | Aarch64Inst::Bvc { label }
            | Aarch64Inst::Cbz { label, .. }
            | Aarch64Inst::Cbnz { label, .. } => {
                self.record_jump_target(*label);
            }

            // Ret doesn't affect our verification (epilogue handles cleanup)
            Aarch64Inst::Ret => {
                // The epilogue (generated by emitter) will restore SP.
                // We don't verify epilogue correctness here since it's
                // generated separately and correct by construction.
            }

            // All other instructions don't affect stack depth
            _ => {}
        }

        Ok(())
    }

    fn record_jump_target(&mut self, label: LabelId) {
        // Record the expected depth at this jump target.
        // If we've already seen the label, the depth was recorded there.
        // If not, this is a forward jump and we record the expected depth.
        // Mismatches are caught when the label is encountered in verify_instruction.
        self.label_depths.entry(label).or_insert(self.current_depth);
    }

    fn alignment_error(&self, idx: usize, inst: &Aarch64Inst, message: String) -> CompileError {
        CompileError::without_span(ErrorKind::InternalCodegenError(format!(
            "stack alignment verification failed at instruction {}: {} (depth: {} bytes) - {}",
            idx, inst, self.current_depth, message
        )))
    }
}

/// Check if an operand is the stack pointer.
fn is_sp(op: &Operand) -> bool {
    matches!(op, Operand::Physical(Reg::Sp))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::aarch64::{Cond, Operand, Reg};

    fn make_mir(instructions: Vec<Aarch64Inst>) -> Aarch64Mir {
        let mut mir = Aarch64Mir::new();
        for inst in instructions {
            mir.push(inst);
        }
        mir
    }

    #[test]
    fn test_empty_function() {
        let mir = make_mir(vec![Aarch64Inst::Ret]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_balanced_stp_ldp() {
        let mir = make_mir(vec![
            // Push two registers (16 bytes)
            Aarch64Inst::StpPre {
                src1: Operand::Physical(Reg::X19),
                src2: Operand::Physical(Reg::X20),
                offset: -16,
            },
            // Pop them back
            Aarch64Inst::LdpPost {
                dst1: Operand::Physical(Reg::X19),
                dst2: Operand::Physical(Reg::X20),
                offset: 16,
            },
            Aarch64Inst::Ret,
        ]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_call_after_aligned_push() {
        // Two STP operations = 32 bytes, still aligned
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("foo");
        mir.push(Aarch64Inst::StpPre {
            src1: Operand::Physical(Reg::X19),
            src2: Operand::Physical(Reg::X20),
            offset: -16,
        });
        mir.push(Aarch64Inst::StpPre {
            src1: Operand::Physical(Reg::X21),
            src2: Operand::Physical(Reg::X22),
            offset: -16,
        });
        mir.push(Aarch64Inst::Bl { symbol_id: sym_id });
        mir.push(Aarch64Inst::LdpPost {
            dst1: Operand::Physical(Reg::X21),
            dst2: Operand::Physical(Reg::X22),
            offset: 16,
        });
        mir.push(Aarch64Inst::LdpPost {
            dst1: Operand::Physical(Reg::X19),
            dst2: Operand::Physical(Reg::X20),
            offset: 16,
        });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_aligned_call() {
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("test_func");
        mir.push(Aarch64Inst::Bl { symbol_id: sym_id });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_sub_add_sp_balanced() {
        // Sub SP, then call, then add SP back
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // Allocate 32 bytes (aligned)
        mir.push(Aarch64Inst::SubImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 32,
        });
        // Call (should be aligned)
        mir.push(Aarch64Inst::Bl { symbol_id: sym_id });
        // Deallocate
        mir.push(Aarch64Inst::AddImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 32,
        });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_unaligned_sub_sp_fails() {
        // Sub SP by 8 (not 16-aligned), then call - should fail
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // Allocate 8 bytes (misaligned!)
        mir.push(Aarch64Inst::SubImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 8,
        });
        // Call without proper alignment - should fail
        mir.push(Aarch64Inst::Bl { symbol_id: sym_id });
        mir.push(Aarch64Inst::Ret);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("alignment"));
    }

    #[test]
    fn test_jump_with_consistent_depth() {
        let mut mir = Aarch64Mir::new();
        let label = mir.alloc_label();

        mir.push(Aarch64Inst::CmpImm {
            src: Operand::Physical(Reg::X0),
            imm: 0,
        });
        mir.push(Aarch64Inst::BCond {
            cond: Cond::Eq,
            label,
        });
        // Fall through path: no stack changes
        mir.push(Aarch64Inst::Label { id: label });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_multiple_calls_aligned() {
        let mut mir = Aarch64Mir::new();
        let sym1 = mir.intern_symbol("func1");
        let sym2 = mir.intern_symbol("func2");

        mir.push(Aarch64Inst::Bl { symbol_id: sym1 });
        mir.push(Aarch64Inst::Bl { symbol_id: sym2 });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_cbz_cbnz_branches() {
        let mut mir = Aarch64Mir::new();
        let label1 = mir.alloc_label();
        let label2 = mir.alloc_label();

        mir.push(Aarch64Inst::Cbz {
            src: Operand::Physical(Reg::X0),
            label: label1,
        });
        mir.push(Aarch64Inst::Cbnz {
            src: Operand::Physical(Reg::X1),
            label: label2,
        });
        mir.push(Aarch64Inst::Label { id: label1 });
        mir.push(Aarch64Inst::Label { id: label2 });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_overflow_branch() {
        let mut mir = Aarch64Mir::new();
        let label = mir.alloc_label();

        mir.push(Aarch64Inst::Bvs { label });
        mir.push(Aarch64Inst::Label { id: label });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }
}
