//! Code generation for the Rue compiler.
//!
//! This crate converts CFG (Control Flow Graph) to machine code.
//! Supports x86-64 and AArch64.
//!
//! ## Pipeline
//!
//! ```text
//! CFG → MIR (virtual registers) → Register Allocation → Machine Code
//! ```
//!
//! Each backend uses a Machine IR (MIR) that closely matches the target
//! instructions but uses virtual registers. Register allocation then maps
//! virtual registers to physical registers before final emission.

mod stack_frame;

pub mod aarch64;
pub mod cfg_lower;
pub mod index_map;
pub mod liveness;
pub mod regalloc;
pub mod types;
pub mod vreg;
pub mod x86_64;

/// The kind of relocation emitted by the code generator.
///
/// This represents the semantic intent of the relocation. The linker
/// will map these to architecture-specific ELF/Mach-O relocation types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelocationKind {
    // ========== x86-64 relocations ==========
    /// 32-bit PC-relative relocation (x86-64).
    /// Used for string constant references and data access.
    X86Pc32,

    /// 32-bit PLT-relative relocation (x86-64).
    /// Used for function calls. For static linking, treated same as PC32.
    X86Plt32,

    // ========== AArch64 relocations ==========
    /// ADRP page-relative relocation (AArch64).
    /// Loads the page address of a symbol into a register.
    Aarch64AdrpPage21,

    /// ADD page offset relocation (AArch64).
    /// Adds the within-page offset of a symbol.
    Aarch64AddLo12,

    /// Branch with link relocation (AArch64).
    /// Used for function calls.
    Aarch64Call26,
}

/// A relocation emitted by the code generator.
///
/// Relocations are recorded for all symbol references (like function calls)
/// that need to be resolved by the linker.
#[derive(Debug, Clone)]
pub struct EmittedRelocation {
    /// Byte offset within the generated code where the relocation applies.
    pub offset: u64,
    /// The symbol name being referenced.
    pub symbol: String,
    /// The kind of relocation.
    pub kind: RelocationKind,
    /// Addend value to add to the symbol address.
    pub addend: i64,
}

impl EmittedRelocation {
    // ========== x86-64 relocation helpers ==========

    /// Create a PC-relative relocation for x86-64.
    ///
    /// Used for string constant references and RIP-relative data access.
    /// The addend is -4 because the displacement is calculated from the
    /// end of the instruction (after the 4-byte displacement field).
    pub fn x86_pc32(offset: u64, symbol: impl Into<String>) -> Self {
        Self {
            offset,
            symbol: symbol.into(),
            kind: RelocationKind::X86Pc32,
            addend: -4,
        }
    }

    /// Create a PLT-relative relocation for x86-64 function calls.
    ///
    /// For static linking, this is treated the same as PC32.
    /// The addend is -4 because the displacement is calculated from the
    /// end of the instruction.
    pub fn x86_call(offset: u64, symbol: impl Into<String>) -> Self {
        Self {
            offset,
            symbol: symbol.into(),
            kind: RelocationKind::X86Plt32,
            addend: -4,
        }
    }

    // ========== AArch64 relocation helpers ==========

    /// Create an ADRP page relocation for AArch64.
    ///
    /// Loads the 4KB-aligned page address of the symbol.
    /// Used as the first part of a two-instruction sequence for
    /// PC-relative data access.
    pub fn aarch64_adrp(offset: u64, symbol: impl Into<String>) -> Self {
        Self {
            offset,
            symbol: symbol.into(),
            kind: RelocationKind::Aarch64AdrpPage21,
            addend: 0,
        }
    }

    /// Create an ADD page offset relocation for AArch64.
    ///
    /// Adds the within-page (12-bit) offset of the symbol.
    /// Used as the second part of a two-instruction sequence for
    /// PC-relative data access.
    pub fn aarch64_add_lo12(offset: u64, symbol: impl Into<String>) -> Self {
        Self {
            offset,
            symbol: symbol.into(),
            kind: RelocationKind::Aarch64AddLo12,
            addend: 0,
        }
    }

    /// Create a branch-with-link relocation for AArch64 function calls.
    ///
    /// Used for the BL instruction.
    pub fn aarch64_call(offset: u64, symbol: impl Into<String>) -> Self {
        Self {
            offset,
            symbol: symbol.into(),
            kind: RelocationKind::Aarch64Call26,
            addend: 0,
        }
    }
}

/// Machine code generated by a backend.
#[derive(Debug)]
pub struct MachineCode {
    /// The generated machine code bytes.
    pub code: Vec<u8>,
    /// Relocations that need to be resolved by the linker.
    pub relocations: Vec<EmittedRelocation>,
    /// String table referenced by the code.
    pub strings: Vec<String>,
}

/// A single emitted machine instruction.
///
/// This captures both the machine code bytes and the human-readable assembly text
/// for an instruction. The emitter produces a sequence of these, which can then
/// be serialized to either raw bytes or assembly text.
#[derive(Debug, Clone)]
pub struct EmittedInst {
    /// The machine code bytes for this instruction.
    /// Empty for labels and comments.
    pub bytes: Vec<u8>,
    /// Human-readable assembly text (e.g., "mov rax, rbx").
    /// For labels, this is just the label text (e.g., "loop:").
    /// For comments, this starts with "; ".
    pub asm: String,
}

impl EmittedInst {
    /// Create a new instruction with bytes and assembly text.
    pub fn new(bytes: impl Into<Vec<u8>>, asm: impl Into<String>) -> Self {
        Self {
            bytes: bytes.into(),
            asm: asm.into(),
        }
    }

    /// Create a label (no bytes, just marks a position).
    pub fn label(name: impl Into<String>) -> Self {
        Self {
            bytes: vec![],
            asm: format!("{}:", name.into()),
        }
    }

    /// Create a comment (no bytes).
    pub fn comment(text: impl Into<String>) -> Self {
        Self {
            bytes: vec![],
            asm: format!("; {}", text.into()),
        }
    }
}

/// Result of emitting a function's machine code.
///
/// This holds all emitted instructions along with metadata needed for
/// linking (relocations, labels for fixups).
#[derive(Debug)]
pub struct EmittedCode {
    /// All emitted instructions in order.
    pub instructions: Vec<EmittedInst>,
    /// Relocations that need to be resolved by the linker.
    pub relocations: Vec<EmittedRelocation>,
}

impl EmittedCode {
    /// Create a new empty EmittedCode.
    pub fn new() -> Self {
        Self {
            instructions: Vec::new(),
            relocations: Vec::new(),
        }
    }

    /// Get the raw machine code bytes.
    pub fn to_bytes(&self) -> Vec<u8> {
        self.instructions
            .iter()
            .flat_map(|inst| inst.bytes.iter().copied())
            .collect()
    }

    /// Get the assembly text representation with byte offsets.
    pub fn to_asm(&self) -> String {
        let mut result = String::new();
        let mut offset = 0usize;

        for inst in &self.instructions {
            if inst.bytes.is_empty() {
                // Label or comment - no offset prefix
                result.push_str(&inst.asm);
            } else {
                // Instruction with bytes - show offset
                result.push_str(&format!("{:4x}:   {}", offset, inst.asm));
            }
            result.push('\n');
            offset += inst.bytes.len();
        }

        result
    }

    /// Get the total size in bytes.
    pub fn len(&self) -> usize {
        self.instructions.iter().map(|i| i.bytes.len()).sum()
    }

    /// Check if empty.
    pub fn is_empty(&self) -> bool {
        self.instructions.is_empty()
    }
}

impl Default for EmittedCode {
    fn default() -> Self {
        Self::new()
    }
}

// Re-export the generate function for x86_64 (default)
pub use x86_64::generate;

// Re-export shared types
pub use index_map::{Handle, IndexMap};
pub use regalloc::{InstructionLiveness, LivenessDebugInfo};
pub use stack_frame::{
    ArgumentLocation, ReturnLocation, StackFrameInfo, StackSlot, generate_stack_frame_info,
};
pub use vreg::{LabelId, VReg};

// Re-export commonly used x86_64 types for convenience
pub use x86_64::{Operand, Reg, X86Inst, X86Mir};

#[cfg(test)]
mod tests {
    use super::*;
    use rue_air::{Air, AirInst, AirInstData, Type};
    use rue_cfg::CfgBuilder;
    use rue_span::Span;

    #[test]
    fn test_generate_x86_64() {
        let mut air = Air::new(Type::I32);

        let const_ref = air.add_inst(AirInst {
            data: AirInstData::Const(42),
            ty: Type::I32,
            span: Span::new(0, 2),
        });

        air.add_inst(AirInst {
            data: AirInstData::Ret(Some(const_ref)),
            ty: Type::I32,
            span: Span::new(0, 2),
        });

        // Build CFG from AIR (no struct/array types in this simple test)
        let cfg_output = CfgBuilder::build(&air, 0, 0, "main", &[], &[], vec![]);

        // Test the generate function
        let machine_code = generate(&cfg_output.cfg, &[], &[], &[]).unwrap();

        // Should generate working code
        assert!(!machine_code.code.is_empty());

        // Code should end with call rel32 (E8 xx xx xx xx)
        // The last 5 bytes should be the call instruction
        let len = machine_code.code.len();
        assert!(len >= 5);
        assert_eq!(machine_code.code[len - 5], 0xE8); // call opcode

        // Should have one relocation for __rue_exit
        assert_eq!(machine_code.relocations.len(), 1);
        assert_eq!(machine_code.relocations[0].symbol, "__rue_exit");

        // Should have no strings
        assert!(machine_code.strings.is_empty());
    }
}
