//! Code generation for the Rue compiler.
//!
//! This crate converts CFG (Control Flow Graph) to machine code.
//! Supports x86-64 and AArch64.
//!
//! ## Pipeline
//!
//! ```text
//! CFG → MIR (virtual registers) → Register Allocation → Machine Code
//! ```
//!
//! Each backend uses a Machine IR (MIR) that closely matches the target
//! instructions but uses virtual registers. Register allocation then maps
//! virtual registers to physical registers before final emission.

pub mod aarch64;
pub mod types;
pub mod vreg;
pub mod x86_64;

/// A relocation emitted by the code generator.
///
/// Relocations are recorded for all symbol references (like function calls)
/// that need to be resolved by the linker.
#[derive(Debug, Clone)]
pub struct EmittedRelocation {
    /// Byte offset within the generated code where the relocation applies.
    pub offset: u64,
    /// The symbol name being referenced.
    pub symbol: String,
    /// Addend value to add to the symbol address.
    pub addend: i64,
}

/// Machine code generated by a backend.
#[derive(Debug)]
pub struct MachineCode {
    /// The generated machine code bytes.
    pub code: Vec<u8>,
    /// Relocations that need to be resolved by the linker.
    pub relocations: Vec<EmittedRelocation>,
    /// String table referenced by the code.
    pub strings: Vec<String>,
}

// Re-export the generate function for x86_64 (default)
pub use x86_64::generate;

// Re-export shared types
pub use vreg::{LabelId, VReg};

// Re-export commonly used x86_64 types for convenience
pub use x86_64::{Operand, Reg, X86Inst, X86Mir};

#[cfg(test)]
mod tests {
    use super::*;
    use rue_air::{Air, AirInst, AirInstData, Type};
    use rue_cfg::CfgBuilder;
    use rue_span::Span;

    #[test]
    fn test_generate_x86_64() {
        let mut air = Air::new(Type::I32);

        let const_ref = air.add_inst(AirInst {
            data: AirInstData::Const(42),
            ty: Type::I32,
            span: Span::new(0, 2),
        });

        air.add_inst(AirInst {
            data: AirInstData::Ret(Some(const_ref)),
            ty: Type::I32,
            span: Span::new(0, 2),
        });

        // Build CFG from AIR
        let cfg_output = CfgBuilder::build(&air, 0, 0, "main");

        // Test the generate function
        let machine_code = generate(&cfg_output.cfg, &[], &[], &[]).unwrap();

        // Should generate working code
        assert!(!machine_code.code.is_empty());

        // Code should end with call rel32 (E8 xx xx xx xx)
        // The last 5 bytes should be the call instruction
        let len = machine_code.code.len();
        assert!(len >= 5);
        assert_eq!(machine_code.code[len - 5], 0xE8); // call opcode

        // Should have one relocation for __rue_exit
        assert_eq!(machine_code.relocations.len(), 1);
        assert_eq!(machine_code.relocations[0].symbol, "__rue_exit");

        // Should have no strings
        assert!(machine_code.strings.is_empty());
    }
}
