//! Stack alignment verification for x86-64.
//!
//! This module provides compile-time verification that the stack remains properly
//! aligned throughout function execution. The System V AMD64 ABI requires RSP to
//! be 16-byte aligned at call sites.
//!
//! # Background
//!
//! After a `call` instruction, RSP points to the return address (8 bytes), leaving
//! RSP 8 bytes below a 16-byte boundary. Functions must ensure that before any
//! nested calls, RSP is again 16-byte aligned.
//!
//! # Verification Strategy
//!
//! We track a "stack depth" representing how many bytes have been pushed relative
//! to the aligned state after the prologue's `sub rsp, N`. Instructions that modify
//! the stack update this depth:
//!
//! - `push r64`: depth += 8
//! - `pop r64`: depth -= 8
//! - `call`: verify depth == 0 (RSP is 16-byte aligned)
//!
//! Note: The prologue is generated by the emitter, not present in the MIR. The
//! prologue ends with RSP 16-byte aligned, so we start verification with depth = 0.
//!
//! # Limitations
//!
//! This verification pass operates on the instruction stream before emission,
//! when the prologue hasn't been added yet. We verify that the body of the function
//! maintains alignment assuming the prologue left RSP aligned.
//!
//! The prologue's alignment is correct by construction (see `emit_prologue` in emit.rs).

use std::collections::HashMap;

use super::mir::{LabelId, Operand, Reg, X86Inst, X86Mir};
use gruel_error::{CompileError, CompileResult, ice_error};

/// Verifies that the stack is properly aligned throughout function execution.
///
/// This checks that:
/// 1. All call instructions occur when RSP is 16-byte aligned
/// 2. Push/pop sequences are balanced within basic blocks
/// 3. Control flow joins have consistent stack depths
///
/// # Arguments
///
/// * `mir` - The MIR instructions to verify (post-regalloc, pre-emit)
///
/// # Returns
///
/// `Ok(())` if verification passes, or `Err(CompileError)` with details about
/// the first alignment violation found.
pub fn verify_stack_alignment(mir: &X86Mir) -> CompileResult<()> {
    let mut verifier = StackVerifier::new();
    verifier.verify(mir)
}

/// Internal state for stack verification.
struct StackVerifier {
    /// Stack depth at each label (for join point verification).
    /// After prologue, depth should be 0 (aligned).
    label_depths: HashMap<LabelId, i64>,
    /// Current stack depth in bytes relative to 16-byte aligned RSP.
    /// 0 = aligned, 8 = misaligned by 8, etc.
    current_depth: i64,
}

impl StackVerifier {
    fn new() -> Self {
        Self {
            label_depths: HashMap::new(),
            current_depth: 0,
        }
    }

    fn verify(&mut self, mir: &X86Mir) -> CompileResult<()> {
        // First pass: collect label positions and do basic verification
        for (idx, inst) in mir.iter().enumerate() {
            self.verify_instruction(idx, inst)?;
        }
        Ok(())
    }

    fn verify_instruction(&mut self, idx: usize, inst: &X86Inst) -> CompileResult<()> {
        match inst {
            // Instructions that increase stack depth (push onto stack)
            X86Inst::Push { .. } => {
                self.current_depth += 8;
            }

            // Instructions that decrease stack depth (pop from stack)
            X86Inst::Pop { .. } => {
                self.current_depth -= 8;
                // Note: We allow negative depths since the epilogue may pop
                // callee-saved registers before we've tracked their pushes
                // (they're in the prologue which isn't in the MIR)
            }

            // AddRI on RSP: used to deallocate stack space (positive imm) or
            // allocate stack space (negative imm, though rare in current codegen)
            X86Inst::AddRI {
                dst: Operand::Physical(Reg::Rsp),
                imm,
            } => {
                // add rsp, N → decreases depth (deallocates)
                // add rsp, -N → increases depth (allocates)
                self.current_depth -= *imm as i64;
            }
            X86Inst::AddRI { .. } => {}

            // Call instructions require 16-byte alignment
            X86Inst::CallRel { .. } => {
                // At a call site, RSP must be 16-byte aligned.
                // Since the call will push an 8-byte return address,
                // the callee will see RSP 8 bytes below a 16-byte boundary,
                // which is correct (they'll push RBP to realign).
                //
                // Our depth tracking starts at 0 (aligned after prologue).
                // If depth % 16 != 0, we're misaligned.
                if self.current_depth % 16 != 0 {
                    return Err(self.alignment_error(
                        idx,
                        inst,
                        format!(
                            "call requires 16-byte aligned RSP, but stack is {} bytes off",
                            self.current_depth % 16
                        ),
                    ));
                }
            }

            // Labels mark potential join points
            X86Inst::Label { id } => {
                if let Some(&expected_depth) = self.label_depths.get(id) {
                    // We've seen a jump to this label before
                    if expected_depth != self.current_depth {
                        return Err(self.alignment_error(
                            idx,
                            inst,
                            format!(
                                "control flow join has inconsistent stack depth: expected {}, got {}",
                                expected_depth, self.current_depth
                            ),
                        ));
                    }
                } else {
                    // First time seeing this label, record current depth
                    self.label_depths.insert(*id, self.current_depth);
                }
            }

            // Jump instructions record target depths
            X86Inst::Jz { label }
            | X86Inst::Jnz { label }
            | X86Inst::Jo { label }
            | X86Inst::Jno { label }
            | X86Inst::Jb { label }
            | X86Inst::Jae { label }
            | X86Inst::Jbe { label }
            | X86Inst::Jge { label }
            | X86Inst::Jle { label }
            | X86Inst::Jmp { label } => {
                self.record_jump_target(*label);
            }

            // Ret doesn't affect our verification (epilogue handles cleanup)
            X86Inst::Ret => {
                // The epilogue (generated by emitter) will restore RSP.
                // We don't verify epilogue correctness here since it's
                // generated separately and correct by construction.
            }

            // All other instructions don't affect stack depth
            _ => {}
        }

        Ok(())
    }

    fn record_jump_target(&mut self, label: LabelId) {
        // Record the expected depth at this jump target.
        // If we've already seen the label, the depth was recorded there.
        // If not, this is a forward jump and we record the expected depth.
        // Mismatches are caught when the label is encountered in verify_instruction.
        self.label_depths.entry(label).or_insert(self.current_depth);
    }

    fn alignment_error(&self, idx: usize, inst: &X86Inst, message: String) -> CompileError {
        ice_error!(
            "stack alignment verification failed",
            phase: "codegen/verify",
            details: {
                "instruction_index" => idx.to_string(),
                "instruction" => inst.to_string(),
                "stack_depth_bytes" => self.current_depth.to_string(),
                "message" => message
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::x86_64::{Operand, Reg};

    fn make_mir(instructions: Vec<X86Inst>) -> X86Mir {
        let mut mir = X86Mir::new();
        for inst in instructions {
            mir.push(inst);
        }
        mir
    }

    #[test]
    fn test_empty_function() {
        let mir = make_mir(vec![X86Inst::Ret]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_balanced_push_pop() {
        let mir = make_mir(vec![
            X86Inst::Push {
                src: Operand::Physical(Reg::Rax),
            },
            X86Inst::Push {
                src: Operand::Physical(Reg::Rbx),
            },
            X86Inst::Pop {
                dst: Operand::Physical(Reg::Rbx),
            },
            X86Inst::Pop {
                dst: Operand::Physical(Reg::Rax),
            },
            X86Inst::Ret,
        ]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_call_after_even_pushes() {
        // Two pushes = 16 bytes, still aligned
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rbx),
        });
        mir.push(X86Inst::CallRel { symbol_id: sym_id });
        mir.push(X86Inst::Pop {
            dst: Operand::Physical(Reg::Rbx),
        });
        mir.push(X86Inst::Pop {
            dst: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_call_after_odd_pushes_fails() {
        // One push = 8 bytes, misaligned
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::CallRel { symbol_id: sym_id });
        mir.push(X86Inst::Pop {
            dst: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::Ret);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("alignment"));
    }

    #[test]
    fn test_aligned_call() {
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("test_func");
        mir.push(X86Inst::CallRel { symbol_id: sym_id });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_jump_with_consistent_depth() {
        let mut mir = X86Mir::new();
        let label = mir.alloc_label();

        mir.push(X86Inst::CmpRI {
            src: Operand::Physical(Reg::Rax),
            imm: 0,
        });
        mir.push(X86Inst::Jz { label });
        // Fall through path: no pushes
        mir.push(X86Inst::Label { id: label });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_multiple_calls_aligned() {
        let mut mir = X86Mir::new();
        let sym1 = mir.intern_symbol("func1");
        let sym2 = mir.intern_symbol("func2");

        mir.push(X86Inst::CallRel { symbol_id: sym1 });
        mir.push(X86Inst::CallRel { symbol_id: sym2 });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_alignment_padding_with_addri() {
        // Simulates call with odd stack args: sub rsp,8 for padding, push arg, call, add rsp,16
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // sub rsp, 8 (alignment padding) - implemented as add rsp, -8
        mir.push(X86Inst::AddRI {
            dst: Operand::Physical(Reg::Rsp),
            imm: -8,
        });
        // push one arg (8 bytes, total 16, aligned)
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rax),
        });
        // call (should be aligned now)
        mir.push(X86Inst::CallRel { symbol_id: sym_id });
        // cleanup: add rsp, 16 (arg + padding)
        mir.push(X86Inst::AddRI {
            dst: Operand::Physical(Reg::Rsp),
            imm: 16,
        });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_unaligned_after_sub_rsp() {
        // sub rsp, 8 without corresponding push - misaligned call
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // sub rsp, 8 via add rsp, -8
        mir.push(X86Inst::AddRI {
            dst: Operand::Physical(Reg::Rsp),
            imm: -8,
        });
        // call without proper alignment
        mir.push(X86Inst::CallRel { symbol_id: sym_id });
        mir.push(X86Inst::Ret);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
    }
}
