rust_binary(
    name = "rue-ui-tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-test-runner:rue-test-runner",
        "//third-party:libtest-mimic",
    ],
    visibility = ["PUBLIC"],
)
