rust_library(
    name = "rue-intern",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party:string-interner",
    ],
)

rust_test(
    name = "rue-intern-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:string-interner",
    ],
)
