[book]
title = "The Rue Language Specification"
authors = ["The Rue Authors"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false
extra-watch-dirs = ["tools/mdbook-spec/src"]

[preprocessor.spec]
command = "mdbook-spec"

[output.html]
git-repository-url = "https://github.com/rue-language/rue"
edit-url-template = "https://github.com/rue-language/rue/edit/main/docs/spec/{path}"
site-url = "/spec/"
additional-css = ["theme/spec.css"]
additional-js = ["theme/back-to-site.js"]

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30

[output.html.playground]
runnable = false
