rust_library(
    name = "rue-rir",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-intern:rue-intern",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-span:rue-span",
    ],
    visibility = ["PUBLIC"],
)
