rust_binary(
    name = "rue",
    srcs = ["src/main.rs"],
    deps = [
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-rir:rue-rir",
        "//crates/rue-target:rue-target",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "rue-test",
    srcs = ["src/main.rs"],
    deps = [
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-rir:rue-rir",
        "//crates/rue-target:rue-target",
    ],
)
