rust_library(
    name = "rue-lexer",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-error:rue-error",
        "//crates/rue-span:rue-span",
    ],
    visibility = ["PUBLIC"],
)
