rust_library(
    name = "rue-lexer",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-error:rue-error",
        "//crates/rue-span:rue-span",
        "//third-party:logos",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "rue-lexer-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-error:rue-error",
        "//crates/rue-span:rue-span",
        "//third-party:logos",
    ],
)
