rust_binary(
    name = "gruel-fuzz",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = ["-Dwarnings"],
    deps = [
        "//crates/gruel-codegen:gruel-codegen",
        "//crates/gruel-compiler:gruel-compiler",
        "//crates/gruel-lexer:gruel-lexer",
        "//crates/gruel-parser:gruel-parser",
        "//third-party:anyhow",
        "//third-party:proptest",
        "//third-party:rayon",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "gruel-fuzz-test",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = ["-Dwarnings"],
    deps = [
        "//crates/gruel-codegen:gruel-codegen",
        "//crates/gruel-compiler:gruel-compiler",
        "//crates/gruel-lexer:gruel-lexer",
        "//crates/gruel-parser:gruel-parser",
        "//third-party:anyhow",
        "//third-party:proptest",
        "//third-party:rayon",
    ],
)
