rust_binary(
    name = "rue-spec",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-test-runner:rue-test-runner",
        "//third-party:libtest2-mimic",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
    visibility = ["PUBLIC"],
)
