rust_binary(
    name = "rue-spec",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:libtest-mimic",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
    visibility = ["PUBLIC"],
)
