rust_library(
    name = "rue-codegen",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-air:rue-air",
        "//crates/rue-span:rue-span",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "rue-codegen-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-air:rue-air",
        "//crates/rue-span:rue-span",
    ],
)
