rust_library(
    name = "gruel-builtins",
    srcs = glob(["src/**/*.rs"]),
    deps = [],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "gruel-builtins-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [],
)
