rust_binary(
    name = "mdbook-spec",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = [
        "//third-party:anyhow",
        "//third-party:once_cell",
        "//third-party:regex",
        "//third-party:serde",
        "//third-party:serde_json",
    ],
    visibility = ["PUBLIC"],
)
