rust_library(
    name = "rue-test-runner",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
    visibility = ["PUBLIC"],
)
