rust_library(
    name = "rue-test-runner",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-error:rue-error",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "rue-test-runner-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-error:rue-error",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
)
