rust_library(
    name = "gruel-linker",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/gruel-target:gruel-target",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "gruel-linker-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/gruel-target:gruel-target",
    ],
)
