rust_binary(
    name = "gruel-ui-tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/gruel-test-runner:gruel-test-runner",
        "//third-party:libtest2-mimic",
    ],
    visibility = ["PUBLIC"],
)
