rust_library(
    name = "gruel-error",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/gruel-span:gruel-span",
        "//third-party:thiserror",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "gruel-error-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/gruel-span:gruel-span",
        "//third-party:thiserror",
    ],
)
