[package]
name = "gruel-lsp"
version.workspace = true
edition.workspace = true
description = "Language Server Protocol implementation for Gruel (ADR-0091)"

[dependencies]
gruel-compiler.workspace = true
gruel-doc.workspace = true
gruel-util.workspace = true
gruel-parser.workspace = true
gruel-air.workspace = true
gruel-cache.workspace = true
gruel-intrinsics.workspace = true
gruel-rir.workspace = true
gruel-target.workspace = true
lasso.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
walkdir.workspace = true
ignore.workspace = true

arc-swap.workspace = true
dashmap.workspace = true
lsp-types.workspace = true
tokio = { workspace = true }
tokio-util.workspace = true
tower-lsp.workspace = true

[dev-dependencies]
tempfile.workspace = true
toml.workspace = true
