rust_library(
    name = "rue-air",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-error:rue-error",
        "//crates/rue-intern:rue-intern",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-rir:rue-rir",
        "//crates/rue-span:rue-span",
    ],
    visibility = ["PUBLIC"],
)
