rust_library(
    name = "gruel-test-runner",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = ["-Dwarnings"],
    deps = [
        "//crates/gruel-error:gruel-error",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "gruel-test-runner-test",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = ["-Dwarnings"],
    deps = [
        "//crates/gruel-error:gruel-error",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
)
